### ISSUE TITLE
setting a default modal height

### ISSUE THREAD

**Issue by n00kii** [n00kii/egui-modal#6]
continuing discussion from #5 and using solution from https://github.com/n00kii/egui-modal/issues/5#issuecomment-1430568221

basic implementation looks like this:

![image](https://user-images.githubusercontent.com/57325298/218965041-b0fc04cd-4184-4d1b-a2b6-0320da0b8bc3.png)

not too desirable, ideally the contents of the frame would be centered and the title and buttons would be at top and bottom, respectively

**Comment by n00kii** [comment]
also we would want to make sure the height is set even if the user is not using the helper functions

**Comment by apoorv569** [comment]
> also we would want to make sure the height is set even if the user is not using the helper functions

Sorry its been a month. Can you remind me what problem are we facing ATM?

**Comment by apoorv569** [comment]
> fixed in [516ff07](https://github.com/n00kii/egui-modal/commit/516ff0734e267612bda7bae70c6479d427d13af8) by using spacers within the `.frame` method, thanks for the help

Nice. I'll try it out and let you know.
