### ISSUE TITLE
[suggestion] bevy_egui support

### ISSUE THREAD

**Issue by robbiemu** [n00kii/egui-modal#7]
I was hoping I could drop this into a bevy_egui app, which I am building to learn bevy (perhaps I'm the wrong person to get very detailed into what people would want!). But this indicates:

error[E0308]: mismatched types
   --> src/menu.rs:100:14
    |
100 |   Modal::new(contexts.ctx_mut(), LOAD_MAP_MODAL_TITLE).show(|ui| {
    |   ---------- ^^^^^^^^^^^^^^^^^^ expected `&Context`, found `&mut Context`
    |   |
    |   arguments to this function are incorrect
    |
    = note: `bevy_egui::egui::Context` and `egui::context::Context` have similar names, but are actually distinct types

**Comment by n00kii** [comment]
what version of `bevy_egui` are you using? its likely that it is reexporting a different version of `egui`

**Comment by n00kii** [comment]
it seems the latest version of `bevy_egui` uses `egui = "0.21.0"`, but the latest version of this crate uses `egui = "0.22.0"`

**Comment by n00kii** [comment]
closing to inactivity

**Comment by calteran** [comment]
PR #184 hasn't been merged yet.  I'm having this same error with updated bevy_notify and bevy_inspector_egui.  Perhaps this issue should be reopened for visibility?

**Comment by n00kii** [comment]
seems like its been merged, closing again
